# Puerto donde correr\u00e1 la API
server.port=8080

# Conexi\u00f3n a Base de Datos H2 en Memoria
spring.datasource.url=jdbc:h2:mem:utndb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web de H2 (Para que puedas ver tus tablas desde el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# MAGIA DE HIBERNATE: 'update' crea las tablas si no existen
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true