name: CI/CD Pipeline - Spring Boot

on:
  push:
    branches:
      - main

jobs:

  ci:

    name: Integración Continua
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v5

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos al Maven Wrapper
        run: chmod +x mvnw

      - name: Ejecutar tests automatizados
        run: ./mvnw test

  cd:

    name: Entrega Continua
    runs-on: ubuntu-latest

    needs: ci

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v5

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos al Maven Wrapper
        run: chmod +x mvnw

      - name: Generar archivo JAR
        run: ./mvnw package -DskipTests

      - name: Publicar artefacto
        uses: actions/upload-artifact@v5
        with:
          name: project-ci-jar
          path: target/*.jar

  notification:

    name: Notificaciones
    runs-on: ubuntu-latest

    needs:
      - ci
      - cd

    if: always()

    steps:

      - name: Notificación Slack OK
        if: needs.ci.result == 'success' && needs.cd.result == 'success'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: good
          SLACK_TITLE: "PIPELINE EXITOSO"
          SLACK_MESSAGE: "CI/CD ejecutado correctamente"
          SLACK_FOOTER: "GitHub Actions"

      - name: Notificación Slack ERROR
        if: needs.ci.result == 'failure' || needs.cd.result == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: danger
          SLACK_TITLE: "PIPELINE FALLÓ"
          SLACK_MESSAGE: "Hubo errores en el pipeline CI/CD"
          SLACK_FOOTER: "GitHub Actions"
